
project_id = "ghfjdgnnhhxhamcwjodx"

[functions.sync_offline_data]
verify_jwt = true

[functions.get_premium_features]
verify_jwt = false

[functions.ai-translator]
verify_jwt = false

[functions.send-translation-email]
verify_jwt = false

[functions.validate-promo-code]
verify_jwt = false

[functions.export-calendar]
verify_jwt = true
