
import { jsPDF } from 'jspdf';
import { DHL_COLORS } from '@/lib/design-system';

// Rozšířené brand colors
const BRAND_COLORS = {
  primary: '#ff6600', // Orange
  secondary: '#64748b', // Slate gray
  accent: '#f59e0b', // Amber
  success: '#10b981', // Emerald
  light: '#f8fafc', // Light gray
  dark: '#1e293b', // Dark gray
  white: '#ffffff'
};

// Pokročilá konfigurace fontů pro lepší podporu diakritiky
export const initializeEnhancedPDF = (): jsPDF => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
    putOnlyUsedFonts: true,
    compress: true
  });

  // Nastavení metadat dokumentu - odebrána neexistující vlastnost 'producer'
  doc.setProperties({
    title: 'PendlerApp Document',
    subject: 'Generated by PendlerApp',
    author: 'PendlerApp',
    creator: 'PendlerApp PDF System'
  });

  // Použití Helvetica fontu s lepší podporou Unicode
  doc.setFont("helvetica");
  
  // Vylepšená funkce pro správné zobrazení české diakritiky
  const originalText = doc.text.bind(doc);
  doc.text = function(text: string | string[], x: number | number[], y?: number, options?: any): jsPDF {
    let processedText: string | string[];
    
    if (typeof text === 'string') {
      // Normalizace českých znaků pro lepší zobrazení
      processedText = text
        .normalize('NFD') // Rozložení diakritických znamének
        .replace(/[\u0300-\u036f]/g, '') // Odstranění kombinovaných znamének
        .normalize('NFC'); // Opětovné složení
      
      // Fallback na původní text pokud normalizace selže
      try {
        processedText = decodeURIComponent(encodeURIComponent(text));
      } catch (e) {
        processedText = text;
      }
    } else {
      processedText = text.map(t => {
        try {
          return decodeURIComponent(encodeURIComponent(t));
        } catch (e) {
          return t;
        }
      });
    }
    
    return originalText.call(this, processedText, x, y, options);
  };
  
  return doc;
};

// Vylepšená hlavička s moderním designem
export const addEnhancedDocumentHeader = (doc: jsPDF, title: string, subtitle?: string): void => {
  const pageWidth = doc.internal.pageSize.width;
  const marginLeft = 14;
  const headerHeight = 35;
  
  // Moderní gradient pozadí hlavičky
  doc.setFillColor(255, 102, 0); // Orange
  doc.rect(0, 0, pageWidth, headerHeight, 'F');
  
  // Světlá overlay pro lepší čitelnost
  doc.setFillColor(255, 255, 255, 0.1);
  doc.rect(0, 0, pageWidth, headerHeight, 'F');
  
  // Logo a branding sekce
  try {
    const logoWidth = 20;
    const logoHeight = 20;
    doc.addImage('/lovable-uploads/88ef4e0f-4d33-458c-98f4-7b644e5b8588.png', 'PNG', marginLeft, 7, logoWidth, logoHeight);
  } catch (error) {
    // Fallback na moderní textové logo
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("P", marginLeft + 8, 20);
  }
  
  // Název aplikace s moderním stylingem
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("PendlerApp", marginLeft + 25, 15);
  
  // Podtitul aplikace
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Chytrý asistent pro české pendlery", marginLeft + 25, 20);
  
  // Datum a čas vygenerování
  const currentDate = new Date();
  const dateStr = currentDate.toLocaleDateString('cs-CZ', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  const timeStr = currentDate.toLocaleTimeString('cs-CZ', {
    hour: '2-digit',
    minute: '2-digit'
  });
  
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255, 0.8);
  doc.text(`${dateStr}`, pageWidth - marginLeft, 15, { align: "right" });
  doc.text(`${timeStr}`, pageWidth - marginLeft, 20, { align: "right" });
  
  // Hlavní nadpis dokumentu
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(title, pageWidth / 2, headerHeight + 15, { align: "center" });
  
  // Podnadpis pokud je zadán
  if (subtitle) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    doc.text(subtitle, pageWidth / 2, headerHeight + 22, { align: "center" });
  }
  
  // Moderní oddělovací linie
  const gradientY = headerHeight + (subtitle ? 28 : 22);
  doc.setDrawColor(255, 102, 0);
  doc.setLineWidth(2);
  doc.line(marginLeft, gradientY, pageWidth - marginLeft, gradientY);
  
  // Jemná shadow linie
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(marginLeft, gradientY + 1, pageWidth - marginLeft, gradientY + 1);
};

// Vylepšená patička s dodatečnými informacemi
export const addEnhancedDocumentFooter = (doc: jsPDF): void => {
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  const marginLeft = 14;
  const footerHeight = 25;
  const pageCount = doc.getNumberOfPages();
  
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    // Moderní footer pozadí
    doc.setFillColor(248, 250, 252); // Light gray
    doc.rect(0, pageHeight - footerHeight, pageWidth, footerHeight, 'F');
    
    // Oddělovací linie
    doc.setDrawColor(255, 102, 0);
    doc.setLineWidth(1);
    doc.line(marginLeft, pageHeight - footerHeight, pageWidth - marginLeft, pageHeight - footerHeight);
    
    // Informace o stránce
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.setFont("helvetica", "normal");
    doc.text(`Strana ${i} z ${pageCount}`, marginLeft, pageHeight - 15);
    
    // Copyright a branding
    doc.text(
      `PendlerApp © ${new Date().getFullYear()} | www.pendlerapp.cz`,
      pageWidth / 2,
      pageHeight - 15,
      { align: "center" }
    );
    
    // Watermark - jemné logo na pozadí (opravena syntaxe)
    try {
      // Nastavení průhlednosti přímo v SaveGraphicsState
      doc.saveGraphicsState();
      doc.setGState({ opacity: 0.05 });
      doc.addImage('/lovable-uploads/88ef4e0f-4d33-458c-98f4-7b644e5b8588.png', 'PNG', 
        pageWidth / 2 - 25, pageHeight / 2 - 25, 50, 50);
      doc.restoreGraphicsState();
    } catch (error) {
      // Watermark se nepodařilo přidat
    }
    
    // QR kód pro web (pokud je k dispozici)
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text("Vygenerováno systémem PendlerApp", pageWidth - marginLeft, pageHeight - 8, { align: "right" });
  }
};

// Funkce pro vytvoření moderní tabulky
export const createStyledTable = async (
  doc: jsPDF, 
  data: { head: string[][]; body: string[][] }, 
  startY: number,
  options?: any
) => {
  const autoTable = await import("jspdf-autotable");
  
  const defaultOptions = {
    startY,
    theme: 'striped',
    headStyles: { 
      fillColor: [255, 102, 0],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 11,
      halign: 'left'
    },
    bodyStyles: {
      fontSize: 10,
      cellPadding: { top: 6, right: 8, bottom: 6, left: 8 }
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252]
    },
    styles: {
      font: 'helvetica',
      lineColor: [200, 200, 200],
      lineWidth: 0.5
    },
    columnStyles: {
      0: { fontStyle: 'bold', textColor: [50, 50, 50] }
    },
    margin: { left: 14, right: 14 },
    ...options
  };
  
  autoTable.default(doc, {
    head: data.head,
    body: data.body,
    ...defaultOptions
  });
};

// Funkce pro přidání sekce s ikonou
export const addSection = (doc: jsPDF, title: string, yPosition: number, icon?: string): number => {
  // Pozadí sekce
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, yPosition - 2, doc.internal.pageSize.width - 28, 12, 2, 2, 'F');
  
  // Nadpis sekce
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(50, 50, 50);
  doc.text(title, 18, yPosition + 6);
  
  // Dekorativní linie
  doc.setDrawColor(255, 102, 0);
  doc.setLineWidth(2);
  doc.line(18, yPosition + 8, 60, yPosition + 8);
  
  return yPosition + 15;
};

// Funkce pro přidání info boxu
export const addInfoBox = (doc: jsPDF, text: string, yPosition: number, type: 'info' | 'warning' | 'success' = 'info'): number => {
  const colors = {
    info: { bg: [59, 130, 246], border: [37, 99, 235] },
    warning: { bg: [245, 158, 11], border: [217, 119, 6] },
    success: { bg: [16, 185, 129], border: [5, 150, 105] }
  };
  
  const color = colors[type];
  const boxHeight = 20;
  
  // Pozadí info boxu
  doc.setFillColor(color.bg[0], color.bg[1], color.bg[2], 0.1);
  doc.roundedRect(14, yPosition, doc.internal.pageSize.width - 28, boxHeight, 3, 3, 'F');
  
  // Border
  doc.setDrawColor(color.border[0], color.border[1], color.border[2]);
  doc.setLineWidth(1);
  doc.roundedRect(14, yPosition, doc.internal.pageSize.width - 28, boxHeight, 3, 3, 'S');
  
  // Text
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(color.border[0], color.border[1], color.border[2]);
  doc.text(text, 18, yPosition + 12);
  
  return yPosition + boxHeight + 5;
};

// Export všech funkcí
export {
  BRAND_COLORS
};
